trigger:
  branches:
    include:
      - main

variables:
  app_location: "/"
  api_location: null
  output_location: "."

jobs:
- job: build_and_deploy
  displayName: "Build and Deploy DAO WebApp"
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AzureStaticWebApp@0
    inputs:
      app_location: $(app_location)
      api_location: $(api_location)
      output_location: $(output_location)
      azure_static_web_apps_api_token: $(deployment_token)
      # Отримай token в Azure Static Web Apps → Configuration → Deployment
      # Встав вручну у Variables або Pipeline Secrets

trigger:
  branches:
    include:
      - main

variables:
  app_location: "/"
  api_location: null
  output_location: "."

jobs:
- job: build_and_deploy
  displayName: "Build and Deploy DAO WebApp"
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AzureStaticWebApp@0
    inputs:
      app_location: $(app_location)
      api_location: $(api_location)
      output_location: $(output_location)
      azure_static_web_apps_api_token: $(deployment_token)
