name: YAML Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  yamllint:
    name: Run YAML Linter
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install yamllint
      run: sudo apt-get install yamllint

    - name: Run yamllint
      run: yamllint .
