name: Release DAO v2.2

on:
  push:
    tags:
      - 'v2.2.0'

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v2.2.0
          name: AgroProsper DAO v2.2
          body: |
            ✅ Нові функції DAO-фрілансу:
            - SBT-бейдж після задач
            - Заявки від компаній
            - NFT-мінт за гру
            - Telegram інтеграція
name: Release DAO v3.0

on:
  push:
    tags:
      - 'v3.0.0'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v3.0.0
          name: AgroProsper DAO v3.0
          body: |
            🚀 Автоматичне оновлення DAO
            ✅ GOV API-звʼязок
            ✅ SBT бейджі після задач
            ✅ Telegram WebApp-мінт + Edge-інтеграція
name: Release DAO v3.0

on:
  push:
    tags:
      - 'v3.0.0'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v3.0.0
          name: AgroProsper DAO v3.0
          body: |
            🚀 Автоматичне оновлення DAO
            ✅ GOV API-звʼязок
            ✅ SBT бейджі після задач
            ✅ Telegram WebApp-мінт + Edge-інтеграція
name: Release DAO v4.5.0

on:
  push:
    tags:
      - 'v4.5.0'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout Repo
        uses: actions/checkout@v3

      - name: 📦 Build ZIP Package
        run: zip -r agroprosper-v4.5.zip ./docs/*

      - name: 🚀 Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v4.5.0
          name: AgroProsper DAO v4.5.0
          body: |
            🌟 Масштабне оновлення DAO до версії 4.5
            ✅ DAO Academy v2 з іспитами
            ✅ Місії Поле #31–#33 з дронами та SBT
            ✅ Grain Market AI-аналітика
            ✅ Режим “Тиха благодійність” + підтвердження Microsoft Rewards / Банки
            ✅ GovBook v2 презентація для державних структур
            ✅ Telegram WebApp → AI Mission Routing

      - name: 📎 Upload ZIP Asset
        uses: softprops/action-gh-release@v1
        with:
          files: agroprosper-v4.5.zip

      - name: 🧠 Запис у status.json
        run: |
          echo '{
            "version": "v4.5.0",
            "status": "released",
            "date": "'$(date +%Y-%m-%d')'",
            "components": [
              "academy.html", "mission-31.html", "dashboard-ai.html",
              "charity-hub.html", "govbook-v2.html", "telegram-auth.html"
            ]
          }' > ./docs/status.json
